### ISSUE TITLE
comparison to native-buffer-browserify

### ISSUE THREAD

**Issue by max-mapper** [dcodeIO/node-BufferView#1]
hello, i've seen you publish some really cool modules lately, thanks for them!

as opposed to BufferView what is your opinion of the approach taken by https://github.com/feross/native-buffer-browserify?

previously https://github.com/chrisdickinson/bops was the best way to write backing buffer agnostic code, but with native-buffer-browserify (part of browserify 3.0), code that uses `Buffer` works 100% in the browser too, and even has a shim for older browsers that don't have typed arrays.

**Comment by max-mapper** [comment]
also if you use IRC feel free to hang in #stackvm on freenode, its a sort of javascript/node module hackers backchannel

**Comment by dcodeIO** [comment]
I think that browserify's approach is essentially the same and thus also legit, they just take it from the opposing perspective. I personally favor ArrayBuffers, as node's Buffers add another interface to a type that has already been well defined as a web standard with the sole difference that `Buffer#slice` creates a view instead of a copy (which imho is a flaw in the ArrayBuffer spec).

The differences basically are:

browserify's approach adds a wrapper around ArrayBuffers while BufferView adds one around Buffers. From a user's perspective it's better to have no wrapper on the client-side for maximum performance, from a business perspective it's better to have no wrapper on the server-side to save 1/10000 cpus or so.

What I am also trying to accomplish here is to give another project of mine, ByteBuffer.js 3.X, a clean way to use both node Buffers as well as ArrayBuffers as its backing array while being transparently interchangeable. This makes some sense as node.js is the only platform having both. For this, I need a custom library, so that I can implement this as much zero-copy aware as possible and as a result making it easy and fast to work with both Buffers and ArrayBuffers under node.js, somewhat neglecting the fact that it is a Buffer-wrapper.

Also, this way around it makes some extra sense because the Buffer API takes a `noAssert` parameter to skip redundant assertions of offsets and so on, which isn't possible the other way around.

I haven't checked browserify's approach for zero-copy and redundant assertions, though.

Using a shim will make BufferView and especially ByteBuffer.js work in older browsers, too, as both avoid using the array access operator on `Uint8Array` and such like it's not supported by IE 8.

Thanks for the IRC hint, I'll jump in as soon as I find some time :)
